spring:
  application:
    name: reservation-entry
  data:
    mongodb:
      database: reservation-db
      host: localhost
      port: 27017
  kafka:
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      bootstrap-servers: "localhost:9092"