topic:
  name:
    producer: "artemas-topic"

spring:
  application:
    name: reservation-entry
---
spring:
  profiles:
    active:
      - docker
  kafka:
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      bootstrap-servers: "kafka:9092"
    bootstrap-servers:
      - "kafka:9092"

---
spring:
  profiles: dev
  kafka:
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      bootstrap-servers: "localhost:9092"
    bootstrap-servers:
      - "localhost:9092"
