topic:
  name:
    consumer: "artemas-topic"
server:
  port: 8081
spring:
  profiles:
    active: docker
  application:
    name: confirmation-service
  kafka:
    consumer:
      bootstrap-servers: "kafka:9092"
      client-id: "confirmation-service-consumer"
      group-id: "confirmation-service-group"
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: "earliest"
      properties:
        spring.json.value.default.type: com.reservation.message.ReservationMessageJson

---

spring:
  profiles: dev
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      client-id: "confirmation-service-consumer"
      group-id: "confirmation-service-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: "earliest"
      properties:
        spring.json.value.default.type: com.reservation.message.ReservationMessageJson
