server:
  port: 8081
spring:
  application:
    name: confirmation-service
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      client-id: "confirmation-service-consumer"
      group-id: "confirmation-service-group"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      auto-offset-reset: "earliest"
